package Screens;

import ClientOperations.Client;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

public class ChatRoomsApp extends javax.swing.JFrame {

    public LoginScreen loginMenu;
    public MenuScreen mainMenu;
    public RoomsOverlayScreen roomsMenu;
    public ChatRoomsScreen inRoomMenu;
    public UsersScreen allUsersMenu;
    public DirectMessageScreen personelRoomMenu;
    public Client client;

    public ChatRoomsApp() throws IOException {
        initComponents();
        setSize(465, 500);
        client = new Client(this);
        //client.Connect("1.1.1.1", 5000);
        client.Connect("127.0.0.1", 5000);
        loginMenu = new LoginScreen(this);
        mainMenu = new MenuScreen(this);
        roomsMenu = new RoomsOverlayScreen(this);
        inRoomMenu = new ChatRoomsScreen(this);
        allUsersMenu = new UsersScreen(this);
        personelRoomMenu = new DirectMessageScreen(this);
        this.add(loginMenu);

    }

    //change menu to another page
    public void changeMenu(JPanel from, JPanel to) {
        
        this.remove(roomsMenu);
        this.remove(loginMenu);
        this.remove(mainMenu);
        this.remove(roomsMenu);
        this.remove(inRoomMenu);
        this.remove(allUsersMenu);
        this.remove(personelRoomMenu);

        this.add(to);
        this.repaint();
        this.revalidate();
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(450, 500));
        setPreferredSize(new java.awt.Dimension(465, 500));

        jLabel1.setMaximumSize(new java.awt.Dimension(600, 700));
        jLabel1.setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().add(jLabel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatRoomsApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new ChatRoomsApp().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(ChatRoomsApp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
