package Screens;

import javax.swing.JOptionPane;
import Messages.Message;

public class LoginScreen extends javax.swing.JPanel {

    /**
     * Creates new form LoginScreen
     */
    ChatRoomsApp mainFrame;
    public LoginScreen(ChatRoomsApp mainFrame) {
        initComponents();
        this.mainFrame = mainFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        loginMenuHeaderLBL = new javax.swing.JLabel();
        userNameInputLBL = new javax.swing.JLabel();
        userNameINP = new javax.swing.JTextField();
        loginBTN = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(500, 500));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        loginMenuHeaderLBL.setFont(new java.awt.Font("Imprint MT Shadow", 0, 28)); // NOI18N
        loginMenuHeaderLBL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loginMenuHeaderLBL.setText("CHAT ROOMS APP");
        jPanel1.add(loginMenuHeaderLBL);

        userNameInputLBL.setBackground(new java.awt.Color(204, 204, 204));
        userNameInputLBL.setFont(new java.awt.Font("Trebuchet MS", 1, 16)); // NOI18N
        userNameInputLBL.setText("nickname:");
        jPanel1.add(userNameInputLBL);

        userNameINP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameINPActionPerformed(evt);
            }
        });
        jPanel1.add(userNameINP);

        loginBTN.setBackground(new java.awt.Color(204, 255, 204));
        loginBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loginBTN.setText("submit");
        loginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loginBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loginBTN)
                .addContainerGap(270, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void userNameINPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameINPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameINPActionPerformed

    private void loginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTNActionPerformed
        ///control user name -----
        //...
        String userName = userNameINP.getText().toString();
        if(userName.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "You need to input a username");
            return;
        }
        //...
        //finish control user name ----
        //then send a message to server type of username to save client's user name on server.
        Message message = new Message(Message.MessageTypes.USERNAME);
        message.content = userName;
        this.mainFrame.client.Send(message);
        this.mainFrame.client.userName =userName;

    }//GEN-LAST:event_loginBTNActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginBTN;
    private javax.swing.JLabel loginMenuHeaderLBL;
    private javax.swing.JTextField userNameINP;
    private javax.swing.JLabel userNameInputLBL;
    // End of variables declaration//GEN-END:variables
}
